<a href="https://colab.research.google.com/github/munawirmt/EDA-Timeseries-models-in-ML/blob/main/Time_series_with_microsoft_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Time series operations in Microsoft dataset**

ASSIGNMENT:


*   Read microsoft dataset
*   get maximum price of the share from 2022 to 2026
*   which is the date of highest price of stock
*   which is the date of lowest price of stock

In [3]:
import pandas_datareader as pdr
import pandas as pd
import yfinance as yf
from datetime import datetime

In [5]:
df=yf.download('MSFT',start='2022-01-01',end='2026-09-19')
df

/tmp/ipykernel_9037/1141165190.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df=yf.download('MSFT',start='2022-01-01',end='2026-09-19')
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2022-01-03  321.856506  324.981327  317.077934  322.433402  28865100
2022-01-04  316.337524  322.289106  313.558825  321.933333  32674300
2022-01-05  304.194031  313.510804  303.809443  313.308872  40054300
2022-01-06  301.790344  306.424700  299.492385  301.088451  39646100
2022-01-07  301.944244  304.309485  298.146373  302.049993  32720000
...                ...         ...         ...         ...       ...
2026-09-14  505.410004  509.950012  495.339996  497.059998  23091900
2026-09-15  497.119995  505.899994  495.540009  500.059998  17794600
2026-09-16  490.299988  495.970001  487.230011  493.029999  16670300
2026-09-17  497.750000  501.470001  493.170013  497.799988  17841600
2026-09-18  493.779999  498.649994  491.100006  497.970001  39544100

[1182 rows x 5 columns]

In [7]:
print(df.head())

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2022-01-03  321.856506  324.981327  317.077934  322.433402  28865100
2022-01-04  316.337524  322.289106  313.558825  321.933333  32674300
2022-01-05  304.194031  313.510804  303.809443  313.308872  40054300
2022-01-06  301.790344  306.424700  299.492385  301.088451  39646100
2022-01-07  301.944244  304.309485  298.146373  302.049993  32720000

In [9]:
max_price=df['High'].max()
min_price=df['Low'].min()

In [10]:
max_price

Ticker
MSFT    550.013114
dtype: float64

In [11]:
min_price

Ticker
MSFT    206.550078
dtype: float64

In [13]:
max_date=df['High'].idxmax()
min_date=df['Low'].idxmin()

In [14]:
max_date

Ticker
MSFT   2025-07-31
dtype: datetime64[ns]

In [15]:
min_date

Ticker
MSFT   2022-11-04
dtype: datetime64[ns]

In [18]:
print(f"Maximum high 2022-2026: ${max_price.iloc[0]:.2f} on {max_date.iloc[0].date()}")
print(f"Minimum low 2022-2026: ${min_price.iloc[0]:.2f} on {min_date.iloc[0].date()}")

Maximum high 2022-2026: $550.01 on 2025-07-31
Minimum low 2022-2026: $206.55 on 2022-11-04